# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestPrijava():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_prijavakorisnika(self):
    # Test name: prijava korisnika
    # Step # | name | target | value
    # 1 | open | https://ezgrada-2.onrender.com/login | 
    self.driver.get("https://ezgrada-2.onrender.com/login")
    # 2 | setWindowSize | 726x816 | 
    self.driver.set_window_size(726, 816)
    # 3 | click | id=:R2alafnnb: | 
    self.driver.find_element(By.ID, ":R2alafnnb:").click()
    # 4 | type | id=:R2alafnnb: | petar@gmail.com
    self.driver.find_element(By.ID, ":R2alafnnb:").send_keys("petar@gmail.com")
    # 5 | click | id=:R2elafnnb: | 
    self.driver.find_element(By.ID, ":R2elafnnb:").click()
    # 6 | type | id=:R2elafnnb: | novijalozinka
    self.driver.find_element(By.ID, ":R2elafnnb:").send_keys("novijalozinka")
    # 7 | click | css=.css-beuub8 | 
    self.driver.find_element(By.CSS_SELECTOR, ".css-beuub8").click()
    # 8 | mouseOver | css=.css-beuub8 | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".css-beuub8")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 9 | mouseOut | css=.css-beuub8 | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()

